OMXPro/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OMXPro.ViewModels
{
    public class ContactViewModel
    {
        [Key]
        public int id { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }

        [Required(ErrorMessage = "Please Enter Your Name")]
        [Display(Name = "Name:")]
        public string GName { get; set; }
        public string GAddress { get; set; }

        [Required(ErrorMessage = "Please enter an email address.")]
        [Display(Name = "Email Address:")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string GEmail { get; set; }

        public string GSubject { get; set; }
        public string GData { get; set; }
    }
}

OMXPro/Controllers/CarouselController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMXPro.Models;
namespace OMXPro.Controllers
{
    public class CarouselController : Controller
    {
        OmxtechDbContext db = new OmxtechDbContext();
        // GET: Carousel
        public ActionResult Index()
        {
            return View();
        }

        //site top carousle
        public ActionResult siteCarousel()
        {
            var getSitCarousel = db.tbl_articles.Where(x => x.a_loc == "3").ToList();

            return PartialView("_SiteCarousle", getSitCarousel);
        }

    }
}

OMXPro/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMXPro.Models;
using OMXPro.ViewModels;
namespace OMXPro.Controllers
{
    public class HomeController : Controller
    {
        private OmxtechDbContext db = new OmxtechDbContext();
        public ActionResult Index_Draft()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        //This is header partial view
        public ActionResult Header()
        {
           
            return PartialView();
        }

        //Carousel 
        public ActionResult Carousel()
        {
            return PartialView();
        }

        //Product List
        public ActionResult ProductList()
        {
            return PartialView();
        }

        //Product Sliding
        public ActionResult ProductSliding()
        {
            return PartialView();
        }

        //News List and Events
        public ActionResult NewsList()
        {
            return PartialView();
        }

        //Footer
        public ActionResult Footer()
        {
            return PartialView();
        }

        //TODO:Add Site Logo
        public ActionResult siteLogo()
        {

            //get site logo
            var getsitelogo = (from a in db.tbl_images
                               where a.imgrole == "SiteLogo"
                               select a).FirstOrDefault();

            return PartialView("Header", getsitelogo);
        }

        //TODO:Get Socials
        public ActionResult siteSocials()
        {

            //get site Socials
            var getsitesocials = (from a in db.socials
                               select a).ToList();

            return PartialView("_Socials", getsitesocials);
        }

        public ActionResult testMenu()
        {
            return View();
        }

        //TODO:site menu
        public JsonResult GetSiteMenu()
        {
            using (OmxtechDbContext db = new OmxtechDbContext())
            {
                var menu = db.tbl_navmenu.ToList();
                return new JsonResult { Data = menu, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }
    }
}

OMXPro/Controllers/NewsListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMXPro.Models;
namespace OMXPro.Controllers
{
    public class NewsListController : Controller
    {
        OmxtechDbContext db = new OmxtechDbContext();
        // GET: NewsList
        public ActionResult Index()
        {
            return View();
        }

        //News list 
        public ActionResult siteNewsLst()
        {
            var getNewsLst = (from a in db.tbl_articles
                                where a.a_loc == "10"
                                orderby a.a_order ascending
                                select a).ToList();

            return PartialView("_NewsList", getNewsLst);
        }

        //News Sliding 
        public ActionResult siteNewsSliding()
        {
            var getNewsSliding = (from a in db.tbl_articles
                              where a.a_loc == "11"
                              orderby a.a_order ascending
                              select a).ToList();

            return PartialView("_NewsSliding", getNewsSliding);
        }
    }
}

OMXPro/Controllers/ProductListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMXPro.Models;
namespace OMXPro.Controllers
{
    public class ProductListController : Controller
    {
        OmxtechDbContext db = new OmxtechDbContext();
        // GET: ProductList
        public ActionResult Index()
        {
            return View();
        }

        //product list top it shows the products in the top of product list category
        public ActionResult proLstTop()
        {
            var getProLstTop = (from a in db.tbl_articles
                                where a.a_loc == "7"
                                orderby a.a_order ascending
                                select a).ToList();

            return PartialView("_productList_Top",getProLstTop); 
        }

        //product list bottom it shows the products in the bottom of product list category
        public ActionResult proLstBottom()
        {
            var getProLstBottom = (from a in db.tbl_articles
                                where a.a_loc == "8"
                                orderby a.a_order ascending
                                select a).ToList();

            return PartialView("_productList_Bottom", getProLstBottom);
        }
    }
}

OMXPro/Controllers/ProductSlidingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMXPro.Models;
namespace OMXPro.Controllers
{
    public class ProductSlidingController : Controller
    {
        OmxtechDbContext db = new OmxtechDbContext();
        // GET: ProductSliding
        public ActionResult Index()
        {
            return View();
        }

        //product sliding
        public ActionResult productSliding()
        {
            var getProducts=(from a in db.tbl_articles
                            where a.a_loc =="9"
                            select a).ToList();

            return PartialView("_ProductSliding", getProducts);
        }
    }
}

OMXPro/Controllers/SocialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OMXPro.Controllers
{
    public class SocialsController : Controller
    {
        // GET: Socials
        public ActionResult Index()
        {
            return View();
        }
    }
}

OMXPro/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OMXPro/Views/Home/Carousel.cshtml
<!-- Carousel
                ================================================== -->
<div id="myCarousel" class="carousel slide carousel-bg" data-ride="carousel">
@Html.Action("siteCarousel", "Carousel")
</div>

OMXPro/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OMXPro/Views/Home/Footer.cshtml
<!-- /END THE FEATURETTES -->
<!-- FOOTER -->
<footer>
    <div class="row" style="background-color:#295288;">
        <div class="container">
            <div class="col-md-12" >
                <p class="pull-right">
                    <a href="#">Back to top</a>
                </p>
                <p style="text-align:center; color:#fff; font-weight:bold;">
                    &copy; 2016 OMX, Inc. 
                </p>
            </div>
        </div>
    </div>
    
</footer>

OMXPro/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

  <!-- Start of Carousel -->
@Html.Partial("Carousel")
<!-- End of Carousel -->

<!-- Start of product List -->
@Html.Partial("productList")
<!-- End of Product List-->

<!-- Start of Product sliding-->
@Html.Partial("ProductSliding")
<!-- End of Product sliding-->

<!-- Start of News list Events-->
@Html.Partial("NewsList")
<!-- End of News list Events-->

OMXPro/Views/Home/Index_Draft.cshtml
@{
    ViewBag.Title = "Home Page";
}

  <!-- Start of Carousel -->
@Html.Partial("Carousel")
<!-- End of Carousel -->

<!-- Start of product List -->
@Html.Partial("productList")
<!-- End of Product List-->

<!-- Start of Product sliding-->
@Html.Partial("ProductSliding")
<!-- End of Product sliding-->

<!-- Start of News list Events-->
@Html.Partial("NewsList")
<!-- End of News list Events-->

OMXPro/Views/Home/NewsList.cshtml
<!-- Starts of our Latest News -->
<div class="container" style="padding-top: 50px;">
    <div class="row">
        <div class="col-md-6">
            @Html.Action("siteNewsLst", "NewsList")
            <!--End of News Container -->
        </div>

        <!--Starts of Events -->
        <div class="col-md-6">
            <div class="events-container ">
                <div class="controllers">
                    <div class="controllers-btn">
                        <a class="btnleft" aria-hidden="true">
                            <i class="fa fa-angle-right" aria-hidden="true"></i>

                        </a>
                        <a class="btnright" aria-hidden="true">
                            <i class="fa fa-angle-left" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
                <div class="sliderEvents">
                    @Html.Action("siteNewsSliding", "NewsList")
                    @*<div class="item">
                        <div class="row">
                            <div class="col-xs-9 col-sm-9 col-md-9">
                                <h4>
                                    <span>This is just an event title </span>
                                    </h4>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <span class="event-date">Event Date:01/01/2016</span>
                            </div>

                        </div>
                        <div class="row center">
                            <div class="col-xs-12 col-md-12 img-container">
                                <img class="" title="OMXproduct 1" alt="Omax" src="~/Content/Images/DP_webinar.png" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <p class="event-details">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores ullam, dolorem vitae culpa voluptatem sapiente eum. Voluptatum, corporis necessitatibus harum rem accusantium, nam est velit vel dicta, id minima fugit!
                                </p>
                                <!--<div class="price"></div>-->
                            </div>
                        </div>
                        <div class="row center">
                            <div class="col-xs-12 event-link">
                                <a class="btn btn-large btn-primary btn-external-url " href="#" target="_blank">
                                    <i class="fa fa-ticket fa-1x"></i>
                                    Sign up now!
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-xs-9 col-sm-9 col-md-9">
                                <h4>
                                    <span>This is just an event title </span>
                                    </h4>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <span class="event-date">Event Date:01/01/2016</span>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-12 img-container">
                                <img class="img-responsive" title="OMXproduct 1" alt="Omax" src="~/Content/Images/ipvt_square.png" />
                            </div>
                        </div>

                        <div class="row left">
                            <div class="col-xs-12 col-md-12">
                                <p class="event-details">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores ullam, dolorem vitae culpa voluptatem sapiente eum. Voluptatum, corporis necessitatibus harum rem accusantium, nam est velit vel dicta, id minima fugit!
                                </p>
                                <!--<div class="price"></div>-->
                            </div>
                        </div>
                        <div class="row center">
                            <div class="col-xs-12 event-link">
                                <a class="btn btn-large btn-primary btn-external-url " href="#" target="_blank">
                                    <i class="fa fa-ticket fa-1x"></i>
                                    Sign up now!
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-xs-9 col-sm-9 col-md-9">
                                <h4>
                                    <span>This is just an event title </span>
                                    </h4>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <span class="event-date">Event Date:01/01/2016</span>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-12 img-container">
                                <img class="img-responsive" title="OMXproduct 1" alt="Omax" src="~/Content/Images/surveillance_logo_300x300.png" />
                            </div>
                        </div>

                        <div class="row left">
                            <div class="col-xs-12 col-md-12">
                                <p class="event-details">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores ullam, dolorem vitae culpa voluptatem sapiente eum. Voluptatum, corporis necessitatibus harum rem accusantium, nam est velit vel dicta, id minima fugit!
                                </p>
                                <!--<div class="price"></div>-->
                            </div>
                        </div>
                        <div class="row center">
                            <div class="col-xs-12 event-link">
                                <a class="btn btn-large btn-primary btn-external-url " href="#" target="_blank">
                                    <i class="fa fa-ticket fa-1x"></i>
                                    Sign up now!
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-xs-9 col-sm-9 col-md-9">
                                <h4>
                                    <span>This is just an event title </span>
                                    </h4>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <span class="event-date">Event Date:01/01/2016</span>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-12 img-container">
                                <img class="img-responsive" title="OMXproduct 1" alt="Omax" src="~/Content/Images/V3-02.png" />
                            </div>
                        </div>

                        <div class="row left">
                            <div class="col-xs-12 col-md-12">
                                <p class="event-details">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores ullam, dolorem vitae culpa voluptatem sapiente eum. Voluptatum, corporis necessitatibus harum rem accusantium, nam est velit vel dicta, id minima fugit!
                                </p>
                                <!--<div class="price"></div>-->
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 event-link">
                                <a class="btn btn-large btn-primary" href="" target="_blank">
                                    <i class="fa fa-ticket fa-1x"></i>
                                    Sign up now!
                                </a>
                            </div>
                        </div>
                    </div>*@
                </div>
            </div><!--End of Events -->
        </div>
    </div>
</div>
<!-- End of our Latest News -->

OMXPro/Views/Home/ProductList.cshtml
<!-- Marketing messaging and featurettes
    ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="container marketing"  style="padding-bottom:20px;">
    <!-- Three columns of text below the carousel -->
    <div class="row" style="padding-bottom:20px;">
        <div class="col-md-12 marketing-top">
            <h2>Wireless Networking - Enterprise</h2>
            <p>OMX OMW-E Series Introducing X-Sense Smart Antenna Technology </p>
        </div>
    </div>
    @Html.Action("proLstTop", "ProductList")
    @*<div class="row">

        <div class="col-lg-4">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: center;">
                <div class="marketing-top-img">
                    <img class="" src="~/Content/Images/devices_picto.jpg" alt="Generic placeholder image">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: center;">
                <div class="text-center"><h3 class="title">Leading edge IP Products and Solutions</h3></div>
                <p class="rtecenter"><span style="color:#999999;"><span style="font-size:16px;">The Grandstream brand means quality, reliability and innovation. Our award-winning products allow business to be more productive than ever before</span></span></p>
                <a class="btn-primary btn btn-border" style=" text-align:center;" href="/our-products"> Read more</a>

            </div><!-- /.col-lg-4 -->
        </div>
        <div class="col-lg-4">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: center;">
                <div class="marketing-top-img">
                    <img class="" src="~/Content/Images/earth_picto.jpg" alt="Generic placeholder image">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: center;">
                <div class="text-center"><h3 class="title">Leading edge IP Products and Solutions</h3></div>
                <p class="rtecenter">
                    <span style="color: #999999;"><span style="font-size: 16px;">The Grandstream brand means quality, reliability and innovation. Our award-winning products allow business to be more productive than ever before</span></span>
                </p>
                <a class="btn-primary btn btn-border" style="text-align: center;" href="/our-products"> Read more</a>

            </div>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: center;">
                <div class="marketing-top-img">
                    <img class="" src="~/Content/Images/wrench_picto.jpg" alt="Generic placeholder image">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: center;">
                <div class="text-center"><h3 class="title">Leading edge IP Products and Solutions</h3></div>
                <p class="rtecenter"><span style="color:#999999;"><span style="font-size:16px;">The Grandstream brand means quality, reliability and innovation. Our award-winning products allow business to be more productive than ever before</span></span></p>
                <a class="btn-primary btn btn-border" style="text-align: center;" href="/our-products"> Read more</a>

            </div>
        </div><!-- /.col-lg-4 -->
    </div>*@<!-- /.row -->
    <!-- START THE FEATURETTES -->
</div><!-- /.container -->
<div class="product-block" style="padding-bottom: 40px; padding-top: 50px;">
    <div style="background-image: url('../../Content/Images/fond-grandstream.jpg');" class="pro-bg-fixed"></div>
    @Html.Action("proLstBottom", "ProductList")

    @*<div class="row" style="padding-bottom: 80px;">
        <div style="text-align: center;" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="white-text text-center">
                <h2 class="title">Our Products and Solutions</h2>
            </div>
            <p class="rtecenter"><span style="color: rgb(255, 255, 255); font-size: 16px;">Grandstream designs and manufactures a wide-range of award winning products and solutions</span></p>
        </div>
    </div>
    <div class="row" style="padding-bottom: 45px;">
        <div class="col-sm-4 col-md-4 col-lg-4" style="padding-right: 40px; padding-left: 40px; text-align: center;">
            <div class="caption" style="max-width: 265px; margin-bottom: 10px;">
                <img title="" alt="" class="img-rounded" src="http://www.grandstream.com/sites/default/files/thumb_video-conference.png">
                <div class="description">
                </div>
            </div>
            <div class="white-text text-center">
                <h3 class="title">Business Conferencing</h3>
            </div>
            <p class="rtecenter"><span style="color: #FFFFFF;">Grandstream’s video conferencing solutions offer small and medium sized businesses flexibility and ease-of-installation along with powerful features</span></p>
            <a style="text-align: center;" href="/products/business-conferencing" class="btn-info btn-lg btn btn-border">
                See products
            </a>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-4" style="padding-right: 40px; padding-left: 40px; text-align: center;">
            <div class="caption" style="max-width: 265px; margin-bottom: 10px;">
                <img title="" alt="" class="img-rounded" src="http://www.grandstream.com/sites/default/files/thumb_voice-telephony.png">
                <div class="description">
                </div>
            </div>
            <div class="white-text text-center">
                <h3 class="title">IP Voice Telephony</h3>
            </div>
            <p class="rtecenter"><span style="color: #FFFFFF;">Grandstream offers a wide-range of IP Phones, from small business to enterprise to cordless, to best suit every business and every type of user</span></p>
            <a style="text-align: center;" href="/products/ip-voice-telephony" class="btn-info btn-lg btn btn-border">
                See products
            </a>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-4" style="padding-right: 40px; padding-left: 40px; text-align: center;">
            <div class="caption" style="max-width: 265px; margin-bottom: 10px;">
                <img title="" alt="" class="img-rounded" src="http://www.grandstream.com/sites/default/files/thumb_video-telephony.png">
                <div class="description">
                </div>
            </div>
            <div class="white-text text-center">
                <h3 class="title">IP Video Telephony</h3>
            </div>
            <p class="rtecenter"><span style="color: #FFFFFF;">The GXV3200 series of IP Video Phones for Android &trade; are 6-line IP phones that offer full access to the Google Play Store, multi-platform video calling and more</span></p>
            <a style="text-align: center;" href="/products/ip-video-telephony" class="btn-info btn-lg btn btn-border">
                See products
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4" style="padding-right: 40px; padding-left: 40px; text-align:center;">
            <div class="caption" style="max-width:265px; margin-bottom: 10px;">
                <img title="" alt="" class="img-rounded" src="http://www.grandstream.com/sites/default/files/thumb_video-surveillance.png">
                <div class="description">
                </div>
            </div>
            <div class="white-text text-center"><h3 class="title">IP Video Surveillance</h3></div>
            <p class="rtecenter"><span style="color:#FFFFFF;">With a complete line of IP video surveillance solutions, Grandstream provides everything needed for a video surveillance solution</span></p>
            <a style=" text-align:center;" href="/products/ip-video-surveillance" class="btn-info btn-lg btn btn-border">
                See products
            </a>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-4" style="padding-right: 40px; padding-left: 40px; text-align:center;">
            <div class="caption" style="max-width:265px; margin-bottom: 10px;">
                <img title="" alt="" class="img-rounded" src="http://www.grandstream.com/sites/default/files/Product%20Categories/thumb_gateways-ata.png">
                <div class="description">
                </div>
            </div>
            <div class="white-text text-center"><h3 class="title">Gateways and ATAs</h3></div>
            <p class="rtecenter"><span style="color:#FFFFFF;">Grandstream's wide-range of Gateways and ATAs are trusted by some of the largest service providers in the world</span></p>
            <a style=" text-align:center;" href="/products/gateways-and-atas" class="btn-info btn-lg btn btn-border">
                See products
            </a>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-4" style="margin-bottom: 60px; padding-right: 40px; padding-left: 40px; text-align:center;">
            <div class="caption" style="max-width:265px; margin-bottom: 10px;">
                <img title="" alt="" class="img-rounded" src="http://www.grandstream.com/sites/default/files/thumb_gateway.png">
                <div class="description">
                </div>
            </div>
            <div class="white-text text-center"><h3 class="title">IP PBXs</h3></div>
            <p class="rtecenter"><span style="color:#FFFFFF;">Grandstream’s UCM series of IP PBXs offer an extensive set of unified communication features in easy-to-manage on premise IP PBXs with no licensing fees</span></p>
            <a style=" text-align:center;" href="/products/ip-pbxs" class="btn-info btn-lg btn btn-border">
                See products
            </a>
        </div>
    </div>*@
</div>

OMXPro/Views/Home/_Socials.cshtml
@model IEnumerable<OMXPro.Models.Social>
<ul class="nav navbar-nav navbar-right">
    <!-- OMX social links -->
    @foreach (var itm in Model)
    {
        <li>
            <a class="btn-facebook" target="_blank" href='@itm.Link'><i class="@itm.img"></i></a>
        </li>
    }

</ul>

OMXPro/Views/Home/testMenu.cshtml
<link href="~/Content/siteMenu.css" rel="stylesheet" />
<script src="~/AngularJs/angular.js"></script>
<script src="~/AngularJs/Module.js"></script>
<script src="~/AngularJs/Service.js"></script>
<script src="~/AngularJs/Controller.js"></script>


@{
    Layout = "";
    ViewBag.Title = "Index";
}

<h2>Dynamic menu from database in AngularJS</h2>

@* Html code for show nav menu here, for mak the application simple
    I will add ngapp and ngcontroller here *@

<div ng-app="MyApp">
    <div ng-controller="menuController">
        @* Here first of all we will create a ng-template *@
        <script type="text/ng-template" id="treeMenu">
            <a href="{{menu.URL}}">{{menu.MenuName}}</a>
            @* We will create submenu only when available *@
            <ul ng-if="(SiteMenu | filter:{ParentId : menu.ID}).length > 0">
                <li ng-repeat="menu in SiteMenu | filter:{ParentId : menu.ID}" ng-include="'treeMenu'"></li>
            </ul>
        </script>

        <ul class="main-navigation">
            @* Here we will load only top level menu *@
            <li ng-repeat="menu in SiteMenu | filter:{ParentId : 0}" ng-include="'treeMenu'"></li>
        </ul>

    </div>
</div>